language: generic
os: linux

notifications:
  email: false

cache:
  directories:
    - texlive
    - form

before_install:
  # TeX Live
  - |
    if [ ! -e ./texlive/bin/x86_64-linux/tlmgr ]; then
      wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz -O - | tar -x --gzip
      echo "
      selected_scheme scheme-minimal
      TEXDIR ./texlive
      TEXMFCONFIG ~/.texlive2016/texmf-config
      TEXMFHOME ~/texmf
      TEXMFLOCAL ./texlive/texmf-local
      TEXMFSYSCONFIG ./texlive/texmf-config
      TEXMFSYSVAR ./texlive/texmf-var
      TEXMFVAR ~/.texlive2016/texmf-var
      collection-fontsrecommended 1
      collection-latex 1
      option_doc 0
      option_src 0
      " | sed -e 's/^ *//' >texlive.profile
      ./install-tl-20*/install-tl --profile texlive.profile
    fi
  - export PATH=$(pwd)/texlive/bin/x86_64-linux:$PATH
  - tlmgr install fancyvrb
  # FORM
  - |
    if [ ! -e ./form/form ]; then
      wget https://github.com/vermaseren/form/releases/download/v4.1-20131025/form-4.1-x86_64-linux.tar.gz -O - | tar -x --gzip
      mkdir -p ./form
      mv form-4.1-x86_64-linux/form form/
    fi
  - export PATH=$(pwd)/form:$PATH

script:
  - make check
